services:
  # Serviço do Banco de Dados
  db:
    image: postgres:11-alpine
    container_name: ezops-db
    environment:
      POSTGRES_USER: ezops_user
      POSTGRES_PASSWORD: ezops_password
      POSTGRES_DB: ezops_db
    volumes:
      # Persistência de dados local
      - postgres_data:/var/lib/postgresql/data
      # AUTOMATIZAÇÃO: Roda o create.sql na inicialização (Passo 4 do README)
      - ./database/create.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Serviço da API Backend
  backend:
    build: .
    container_name: ezops-backend
    ports:
      - "3000:3000" # Ajuste a porta da esquerda se sua 3000 estiver ocupada
    environment:
      # Variáveis pedidas no passo 5 do README
      DB_HOST: db         # Nome do serviço acima
      DB_USER: ezops_user
      DB_PASSWORD: ezops_password
      DB_NAME: ezops_db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data: